# Generated by Django 6.0.3 on 2026-04-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_password_reset_token'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE "core"."users"
                    ADD COLUMN IF NOT EXISTS failed_login_attempts SMALLINT NOT NULL DEFAULT 0,
                    ADD COLUMN IF NOT EXISTS is_locked BOOLEAN NOT NULL DEFAULT FALSE;
            """,
            reverse_sql="""
                ALTER TABLE "core"."users"
                    DROP COLUMN IF EXISTS failed_login_attempts,
                    DROP COLUMN IF EXISTS is_locked;
            """,
        ),
    ]
