# Generated by Django 6.0.3 on 2026-05-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_lockout_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='templates/')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='core.indicator')),
            ],
            options={
                'verbose_name': 'Plantilla de indicador',
                'verbose_name_plural': 'Plantillas de indicadores',
                'db_table': '"core"."indicator_templates"',
                'managed': True,
            },
        ),
    ]
