# Generated by Django 6.0.3 on 2026-05-16 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_indicatortemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortemplate',
            name='expected_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='indicatortemplate',
            name='expected_structure',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='indicatortemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indicatortemplate',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='indicatortemplate',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='EvidenceValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_existence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_format', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_update', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_structure', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_content', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_accessibility', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('compliance_status', models.CharField(choices=[('CUMPLE', 'Cumple'), ('CUMPLE_PARCIALMENTE', 'Cumple parcialmente'), ('INCOMPLETO', 'Incompleto'), ('NO_CUMPLE', 'No cumple'), ('NO_PRESENTADO', 'No presentado'), ('ERROR_PROCESAMIENTO', 'Error de procesamiento')], default='NO_PRESENTADO', max_length=25)),
                ('observations', models.JSONField(blank=True, default=list)),
                ('validated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='core.evidence')),
            ],
            options={
                'verbose_name': 'Resultado de validación',
                'verbose_name_plural': 'Resultados de validación',
                'db_table': '"evaluation"."evidence_validation_results"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UniversityEvaluationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_index', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_indicators', models.SmallIntegerField(default=0)),
                ('indicators_compliant', models.SmallIntegerField(default=0)),
                ('indicators_partial', models.SmallIntegerField(default=0)),
                ('indicators_incomplete', models.SmallIntegerField(default=0)),
                ('indicators_non_compliant', models.SmallIntegerField(default=0)),
                ('indicators_not_presented', models.SmallIntegerField(default=0)),
                ('general_observations', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_summaries', to='core.evaluationperiod')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_summaries', to='core.university')),
            ],
            options={
                'verbose_name': 'Resumen de evaluación',
                'verbose_name_plural': 'Resúmenes de evaluación',
                'db_table': '"evaluation"."university_evaluation_summaries"',
                'managed': True,
                'unique_together': {('university', 'period')},
            },
        ),
    ]
