# Generated by Django 6.0.3 on 2026-05-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_validation_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'managed': True, 'verbose_name': 'Usuario del sistema', 'verbose_name_plural': 'Usuarios del sistema'},
        ),
    ]
